### ISSUE TITLE
Elasticsearch v6

### ISSUE THREAD

**Issue by mwaldmueller** [NETWAYS/graphing-training#4]
Update to Elasticsearch v6 incl. Icingabeat

**Comment by dnsmichi** [comment]
You can use the `elastic` box to play with, everything's fully integrated there (requires current git master): https://github.com/icinga/icinga-vagrant

**Comment by mwaldmueller** [comment]
Thanks for the hint, but we need Elasticsearch and Icingabeat natively to show annotations in Grafana and combine them with graphs from Graphite.

**Comment by dnsmichi** [comment]
The one who writes the showoff material, may just use pre-provisioned boxes to start to play with. Same applies to InfluxDB or the Graphite module - I have integrated them all, everything works so far (mainly for Icinga Camp Berlin) :-)

**Comment by mwaldmueller** [comment]
done
